#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Tomohiro Hayashi  s19c1094hn@s.chibakoudai.jp
# SPDX-License-Identifier: BSD-3-Clause

import sys
ans = 0

def plus(x, y):
    x + y
    return x + y

def minus(x, y):
    x - y
    return x - y

def multiply(x, y):
    x * y
    return x * y

def divide(x, y):
    x / y
    return x / y

try:
    num1 = int(input())#"First_number:"))

except EOFError:
    exit

while True:
    try:
        op = input()#("Operator:")
    
    except EOFError:
        break
    
    if op == 'clear':
        num1 = 0
        num1 = int(input())
        op = input()

    try:    
        num2 = int(input())#("Second_number:"))

    except EOFError:
        break

    if op == '+':
        ans = plus(num1,num2)
        print(ans)
        num1 = ans

    elif op == '-':
        ans = minus(num1,num2)
        print(ans)
        num1 = ans
    
    elif op == '*':
        ans = multiply(num1,num2)
        print(ans)
        num1 = ans
    
    elif op == '/':

        if num2 == 0:
            break
        
        ans = divide(num1,num2)
        print(ans)
        num1 = ans

    else:
        break